import type { Lead, Settings, Stage } from './types'

export const STAGES: Stage[] = [
  '1º Contato',
  'Entrevista Marcada',
  'Entrevista Realizada',
  'Pasta Completa',
  'Revisão Advogado',
  'Protocolo Iniciado',
  'Contrato Assinado',
]

export const STAGE_CLASS: Record<Stage | 'Perdido', string> = {
  '1º Contato': 's-contato',
  'Entrevista Marcada': 's-entrevista',
  'Entrevista Realizada': 's-entrevista',
  'Pasta Completa': 's-documentos',
  'Revisão Advogado': 's-documentos',
  'Protocolo Iniciado': 's-protocolo',
  'Contrato Assinado': 's-contrato',
  Perdido: 's-perdido',
}

export const DEFAULT_SETTINGS: Settings = {
  firmName: 'Túlio Lopes Advocacia',
  ownerName: 'Túlio Lopes',
  monthlyProtocolGoal: 12,
  minimumTicket: 6000,
  conversionGoal: 35,
}

export const SAMPLE_LEADS: Lead[] = [
  {
    id: 'seed-1',
    name: 'Maria das Graças Silva',
    phone: '(91) 98765-4321',
    email: 'mgraças@email.com',
    area: 'Previdenciário',
    origin: 'Indicação',
    stage: 'Protocolo Iniciado',
    ticket: 7500,
    owner: 'Túlio Lopes',
    days: 12,
    notes: 'Caso de aposentadoria por invalidez. Documentação médica completa. Urgente.',
    activity: ['Protocolo iniciado — 3 dias atrás', 'Revisão jurídica aprovada — 5 dias atrás', 'Pasta completa confirmada — 8 dias atrás'],
  },
  {
    id: 'seed-2',
    name: 'João Batista Ferreira',
    phone: '(91) 99123-4567',
    email: 'jbatista@gmail.com',
    area: 'Trabalhista',
    origin: 'Tráfego Pago (Instagram)',
    stage: 'Entrevista Marcada',
    ticket: 5500,
    owner: 'Coord. Comercial',
    days: 3,
    notes: 'Demissão sem justa causa. Entrevista agendada para quinta-feira.',
    activity: ['Entrevista agendada para 18/04 — 1 dia atrás', 'Lead qualificado via Instagram — 3 dias atrás'],
  },
  {
    id: 'seed-3',
    name: 'Ana Cristina Pinheiro',
    phone: '(91) 98877-6655',
    email: 'anapinheiro@outlook.com',
    area: 'Previdenciário',
    origin: 'WhatsApp',
    stage: 'Pasta Completa',
    ticket: 8200,
    owner: 'Assistente Jurídico',
    days: 18,
    notes: 'Pensão por morte do cônjuge. Todos os documentos recebidos e organizados.',
    activity: ['Pasta completa confirmada — 2 dias atrás', 'Entrevista realizada — 6 dias atrás', 'Lead recebido via WhatsApp — 18 dias atrás'],
  },
  {
    id: 'seed-4',
    name: 'Carlos Eduardo Mendes',
    phone: '(91) 97654-3210',
    email: 'cemendes@empresa.com',
    area: 'Cível',
    origin: 'Indicação',
    stage: '1º Contato',
    ticket: 6000,
    owner: 'Túlio Lopes',
    days: 1,
    notes: 'Indicação do cliente João B. Contato inicial realizado hoje.',
    activity: ['Primeiro contato realizado — hoje'],
  },
  {
    id: 'seed-5',
    name: 'Rosângela Torres',
    phone: '(91) 99988-7766',
    email: 'rtorres@email.com',
    area: 'Previdenciário',
    origin: 'Tráfego Pago (Google)',
    stage: 'Revisão Advogado',
    ticket: 7000,
    owner: 'Túlio Lopes',
    days: 22,
    notes: 'Auxílio-doença. Documentação médica em revisão pelo advogado.',
    activity: ['Revisão jurídica em andamento — 1 dia atrás', 'Pasta entregue — 4 dias atrás'],
  },
  {
    id: 'seed-6',
    name: 'Francisca Lima',
    phone: '(91) 98811-2233',
    email: 'frlima@gmail.com',
    area: 'Administrativo',
    origin: 'Indicação',
    stage: 'Entrevista Realizada',
    ticket: 9000,
    owner: 'Túlio Lopes',
    days: 7,
    notes: 'Servidor público. Revisão de benefício negado. Checklist entregue na entrevista.',
    activity: ['Entrevista realizada — 2 dias atrás', 'Entrevista marcada — 5 dias atrás', 'Contato via indicação — 7 dias atrás'],
  },
  {
    id: 'seed-7',
    name: 'Pedro Araújo Santos',
    phone: '(91) 99001-2345',
    email: 'pedroarauj@email.com',
    area: 'Trabalhista',
    origin: 'WhatsApp',
    stage: '1º Contato',
    ticket: 4500,
    owner: 'Coord. Comercial',
    days: 2,
    notes: 'Horas extras não pagas. Empresa de médio porte.',
    activity: ['Primeiro contato — 2 dias atrás'],
  },
  {
    id: 'seed-8',
    name: 'Tereza Nascimento',
    phone: '(91) 98765-0011',
    email: 'terezanasci@gmail.com',
    area: 'Previdenciário',
    origin: 'Indicação',
    stage: 'Contrato Assinado',
    ticket: 6800,
    owner: 'Túlio Lopes',
    days: 35,
    notes: 'Aposentadoria rural. Contrato assinado. Protocolo em andamento.',
    activity: ['Contrato assinado — 5 dias atrás', 'Protocolo iniciado — 8 dias atrás'],
  },
  {
    id: 'seed-9',
    name: 'Raimundo Costa Barros',
    phone: '(91) 97788-9900',
    email: 'raimundocb@hotmail.com',
    area: 'Criminal',
    origin: 'Ligação',
    stage: 'Entrevista Marcada',
    ticket: 12000,
    owner: 'Túlio Lopes',
    days: 1,
    notes: 'Caso criminal. Entrevista marcada para amanhã às 14h.',
    activity: ['Entrevista agendada — hoje', 'Ligação recebida — hoje'],
  },
  {
    id: 'seed-10',
    name: 'Marlene Figueiredo',
    phone: '(91) 99234-5678',
    email: 'marlenef@email.com',
    area: 'Previdenciário',
    origin: 'Tráfego Pago (Instagram)',
    stage: 'Protocolo Iniciado',
    ticket: 7200,
    owner: 'Assistente Jurídico',
    days: 14,
    notes: 'BPC-LOAS para pessoa com deficiência. Protocolo administrativo iniciado.',
    activity: ['Protocolo iniciado — 1 dia atrás', 'Revisão aprovada — 3 dias atrás'],
  },
  {
    id: 'seed-11',
    name: 'Benedito Melo Carvalho',
    phone: '(91) 98656-7788',
    email: 'bmelo@gmail.com',
    area: 'Cível',
    origin: 'Site',
    stage: 'Pasta Completa',
    ticket: 5800,
    owner: 'Assistente Jurídico',
    days: 9,
    notes: 'Ação de cobrança. Documentação quase completa, falta 1 contrato.',
    activity: ['Pasta 90% completa — 1 dia atrás', 'Entrevista realizada — 4 dias atrás'],
  },
  {
    id: 'seed-12',
    name: 'Iracema Santos Vieira',
    phone: '(91) 99456-7890',
    email: 'iracema@email.com',
    area: 'Trabalhista',
    origin: 'Indicação',
    stage: '1º Contato',
    ticket: 5000,
    owner: 'Coord. Comercial',
    days: 0,
    notes: 'Rescisão indireta. Lead novo, contato realizado agora.',
    activity: ['Primeiro contato — hoje'],
  },
]
